export const therapyAnimals = [
  { slug: "dog", title: "Dog", color: "#8cc5ff", shape: "dog", available: true },
  { slug: "cat", title: "Cat", color: "#ffc7d9", shape: "cat", available: true },
  { slug: "rabbit", title: "Rabbit", color: "#d5c5ff", available: false },
  { slug: "bird", title: "Bird", color: "#ffe09c", available: false },
  { slug: "fish", title: "Fish", color: "#9fdfff", available: false },
  { slug: "turtle", title: "Turtle", color: "#bce7a3", available: false },
  { slug: "horse", title: "Horse", color: "#c8d8ff", available: false },
  { slug: "elephant", title: "Elephant", color: "#d8dcf2", available: false },
  { slug: "lion", title: "Lion", color: "#ffd08a", available: false },
  { slug: "bear", title: "Bear", color: "#d8c0a8", available: false },
  { slug: "fox", title: "Fox", color: "#ffbf99", available: false },
  { slug: "owl", title: "Owl", color: "#e0d3ff", available: false },
  { slug: "duck", title: "Duck", color: "#ffe79f", available: false },
  { slug: "whale", title: "Whale", color: "#a9d2ff", available: false },
  { slug: "dolphin", title: "Dolphin", color: "#8fdaf0", available: false },
  { slug: "butterfly", title: "Butterfly", color: "#ffc2ef", available: false },
  { slug: "monkey", title: "Monkey", color: "#d6b08a", available: false },
  { slug: "zebra", title: "Zebra", color: "#f3f6ff", available: false },
];
